server {
    server_name www.pictosound.com pictosound.com;
    root /var/www/pictosound;
    index index.html;
location /auth/ {
    proxy_pass http://127.0.0.1:8000/auth/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

location /cerca {
    proxy_pass http://127.0.0.1:8000/cerca;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

location /documenti {
    proxy_pass http://127.0.0.1:8000/documenti;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

location /categorie {
    proxy_pass http://127.0.0.1:8000/categorie;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

location /documento/ {
    proxy_pass http://127.0.0.1:8000/documento/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

location /originale/ {
    proxy_pass http://127.0.0.1:8000/originale/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

location /admin/ {
    proxy_pass http://127.0.0.1:8000/admin/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
    location /api/ {
        proxy_pass http://127.0.0.1:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/www.pictosound.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.pictosound.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    server_name pictosound.com www.pictosound.com;
    return 301 https://www.pictosound.com$request_uri;
}
